spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:urlscanner}
    username: ${DB_USER:urlscanner}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  application:
    name: urlscanner

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:mySecretKeyForJWTWhichNeedsToBeVeryLongForHS256Algorithm}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.geeknarrator.urlscanner: INFO