debug: true # Enable auto-configuration report

spring:
  application:
    name: urlscanner
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME:urlscanner}
    username: ${DB_USER:urlscanner}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Creates/updates the schema on startup
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:default-super-secret-key-that-should-be-changed}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus # Expose prometheus endpoint
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    com.geeknarrator.urlscanner: INFO

# Custom application properties
urlscan:
  api:
    key: ${URLSCAN_API_KEY:}
  cache:
    ttl:
      hours: ${URLSCAN_CACHE_TTL_HOURS:24}
