apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlscanner-app
  namespace: urlscanner
  labels:
    app: urlscanner-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: urlscanner-app
  template:
    metadata:
      labels:
        app: urlscanner-app
    spec:
      containers:
      - name: urlscanner-app
        image: urlscanner:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "urlscanner"
        - name: DB_USER
          value: "urlscanner"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: SERVER_PORT
          value: "8080"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION
          value: "86400000"
        - name: URLSCAN_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: urlscan-api-key
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: urlscanner-service
  namespace: urlscanner
spec:
  selector:
    app: urlscanner-app
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer