apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-sql
  namespace: urlscanner
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        email VARCHAR(255) UNIQUE NOT NULL,
        password VARCHAR(255) NOT NULL,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        is_active BOOLEAN DEFAULT TRUE
    );

    CREATE TABLE IF NOT EXISTS url_scans (
        id SERIAL PRIMARY KEY,
        url VARCHAR(2048) NOT NULL,
        scan_status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        result TEXT,
        user_id BIGINT NOT NULL,
        external_scan_id VARCHAR(255),
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
    );

    CREATE INDEX idx_users_email ON users(email);
    CREATE INDEX idx_url_scans_user_id ON url_scans(user_id);
    CREATE INDEX idx_url_scans_status ON url_scans(scan_status);
    CREATE INDEX idx_url_scans_created_at ON url_scans(created_at);
    CREATE INDEX idx_url_scans_external_scan_id ON url_scans(external_scan_id);