global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'urlscanner'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['urlscanner-app:8080']
